name: Build Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2025-vs2026

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore NNN-Solution/NNN-Solution.sln

      - name: Build ReleasePackage
        shell: cmd
        run: |
          msbuild NNN-Solution/NNN-Solution.sln ^
            /p:Configuration=ReleasePackage ^
            /p:Platform=x64

      - name: Prepare release package
        shell: pwsh
        run: |
          $Version = "${{ github.ref_name }}"
          
          New-Item -ItemType Directory -Force release/Runtime | Out-Null
      
          Copy-Item "**/bin/x64/ReleasePackage/NNN.dll" release/Runtime
          Copy-Item "**/bin/x64/ReleasePackage/NNNCSharp.dll" release/Runtime
      
          Copy-Item LICENSE release
          Copy-Item README.md release
      
          Compress-Archive `
            -Path release/* `
            -DestinationPath "NNN-$Version.zip"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            NNN-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
